version: "3.8"

services:
    akyuu:
        image: akyuu_bot:latest
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - conf.env
        volumes:
            - ./:/akyuu/
        command: bash -c "alembic upgrade head && python __main__.py"
        network_mode: host
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:14-bullseye
        env_file:
            - conf.env
        expose:
            - 5500
        ports:
            - 5500:5500
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        command: -p 5500
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -p 5500"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
