version: "3.8"

services:
    akyuu:
        image: akyuu_bot:latest
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - conf.env
        volumes:
            - ./:/akyuu/
        command: python __main__.py
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:14-bullseye
        env_file:
            - conf.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
